Repository vishipayyallore/eshop-services-configuration, pull requests merged in 2022-10, with the labels that each got.

#6 api host added
  example-local.settings.json
  get-configuration/configuration.type.ts
  get-configuration/configurations/app-settings.ts
Labels: enhancement

#7 update version number
  package.json
Labels: bug

#8 Initial Version of Containerization of Configuration Service
  .dockerignore
  .vscode/launch.json
  .vscode/tasks.json
  Dockerfile
  docker-compose.debug.yml
  docker-compose.yml
  package-lock.json
Labels: documentation, enhancement

#9 Swamy/20oct2022 containerize azfunc
  Dockerfile
  Documentation/Images/Build_Docker_Image.PNG
  Documentation/Images/Configuration_From_Env_File.PNG
  Documentation/Images/Create_Container_Of_Configuration.PNG
  Documentation/Sessions/Session1.md
  README.md
  dev.env
  get-configuration/index.ts
Labels: documentation, enhancement
